###
# Starship configuration
###

###
# Configures the starship schema
###
"$schema" = 'https://starship.rs/config-schema.json'

###
# Configures the add newline
###
add_newline = true

###
# Configures the format
###
format = """
$os\
$directory\
$git_branch$git_status\
$docker_context\
$aws\
$fill\
$php\
$python\
$golang\
$bun\
$dart\
$rust\
$deno\
$julia\
$lua\
$nodejs\
$ruby\
$swift\
$typst\
$time\
$line_break\
$character
"""

###
# Configures the palette
###
palette = 'terminal'

###
# Terminal palette - uses ANSI colors to respect terminal theme
###
[palettes.terminal]
foreground   = 'white'
background   = 'black'
box          = 'bright-black'
primary      = 'black'
current_line = 'bright-black'
error        = 'red'
success      = 'green'
color1       = 'cyan'
color2       = 'green'
color3       = 'yellow'
color4       = 'blue'
color5       = 'magenta'
color6       = 'magenta'
color7       = 'red'

[os.symbols]
Alpaquita        = " "
Alpine           = " "
AlmaLinux        = " "
Amazon           = " "
Android          = " "
Arch             = " "
Artix            = " "
CachyOS          = " "
CentOS           = " "
Debian           = " "
DragonFly        = " "
Emscripten       = " "
EndeavourOS      = " "
Fedora           = " "
FreeBSD          = " "
Garuda           = "󰛓 "
Gentoo           = " "
HardenedBSD      = "󰞌 "
Illumos          = "󰈸 "
Kali             = " "
Linux            = " "
Mabox            = " "
Macos            = " "
Manjaro          = " "
Mariner          = " "
MidnightBSD      = " "
Mint             = " "
NetBSD           = " "
NixOS            = " "
Nobara           = " "
OpenBSD          = "󰈺 "
openSUSE         = " "
OracleLinux      = "󰌷 "
Pop              = " "
Raspbian         = " "
Redhat           = " "
RedHatEnterprise = " "
RockyLinux       = " "
Redox            = "󰀘 "
Solus            = "󰠳 "
SUSE             = " "
Ubuntu           = " "
Unknown          = " "
Void             = " "
Windows          = "󰍲 "

###
# Configures the OS
###
[os]
format = '[ $symbol](fg:primary bg:color2)'
disabled = false

###
# Configures the directory module
###
[directory]
format            = '(fg:current_line)(fg:primary bg:color2)[ $read_only$truncation_symbol$path ](fg:foreground bg:box)'
home_symbol       = "󱂵 ~"
read_only         = '󰌾 '
read_only_style   = ''
truncation_length = 2
truncation_symbol = '󰝰 '

###
# Configures the bun module
###
[bun]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the character module
###
[character]
error_symbol   = '[χ](bold fg:error)'
format         = '$symbol '
success_symbol = '[λ](bold fg:success)'

###
# Configures the dart module
###
[dart]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the deno module
###
[deno]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''


###
# Configures the dotnet module
###
[dotnet]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the elixir module
###
[elixir]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the fill module
###
[fill]
style  = 'fg:current_line'
symbol = '─'

###
# Configures the git branch module
###
[git_branch]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color3)[ $branch ](fg:foreground bg:box)'
symbol = '󰘬'

###
# Configures the git commit module
###
[git_commit]
commit_hash_length = 4
format             = "((fg:current_line)[ 󰓹 ](fg:primary bg:color3)[ $tag ](fg:foreground bg:box))((fg:current_line)[ 󰜘 ](fg:primary bg:color3)[ $hash ](fg:foreground bg:box))"
only_detached      = false
tag_disabled       = false
tag_symbol         = ''

###
# Configures the git status module
###
[git_status]
format = '((fg:primary bg:color3)[\[$all_status$ahead_behind\]](fg:foreground bg:box))'

###
# Configures the golang module
###
[golang]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the helm module
###
[helm]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the julia module
###
[julia]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the kotlin module
###
[kotlin]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the lua module
###
[lua]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the nodejs module
###
[nodejs]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the php module
###
[php]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the python module
###
[python]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the ruby module
###
[ruby]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the rust module
###
[rust]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the scala module
###
[scala]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the swift module
###
[swift]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the package module
###
[package]
format = '(fg:current_line)[ 󰏖 ](fg:primary bg:color4)[ $version ](fg:foreground bg:box)'

###
# Configures the shell module
###
[shell]
disabled          = true
format            = '(fg:current_line)[ 󰆍 ](fg:primary bg:color5)[ $indicator ](fg:foreground bg:box)'
unknown_indicator = 'shell'

###
# Configures the time module
###
[time]
disabled    = false
format      = '(fg:current_line)[ 󰥔 ](fg:primary bg:color1)[ $time ](fg:foreground bg:box)'
time_format = '%H:%M'

###
# Configures the aws module
###
[aws]
disabled = true
format   = '(fg:current_line)[ ☁︎ ](fg:primary bg:color7)([ $region ](fg:foreground bg:box))'

###
# Configures the docker context module
###
[docker_context]
disabled = false
format   = '(fg:current_line)[ 󰡣 ](fg:primary bg:color1)([ $context ](fg:foreground bg:box))'

###
# Configures the typst module
###
[typst]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = 'TYPST'

###
# Configures the username module
###
[username]
format      = '(fg:current_line)[ 󰀄 ](fg:primary bg:color7)[ $user ](fg:foreground bg:box) '
show_always = true

###
# Configures the zig module
###
[zig]
format = '(fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = 'ZIG'
