###
# Starship configuration
###

###
# Configures the starship schema
###
"$schema" = 'https://starship.rs/config-schema.json'

###
# Configures the add newline
###
add_newline = true

###
# Configures the format
###
format = """
$os\
$directory\
$docker_context\
$aws\
$fill\
$git_branch$git_status\
$php\
$python\
$golang\
$bun\
$dart\
$rust\
$deno\
$julia\
$lua\
$nodejs\
$ruby\
$swift\
$typst\
$time\
$line_break\
$character
"""

###
# Configures the palette
###
palette = 'gruvbox'

[palettes.gruvbox]
foreground   = '#fbf1c7'
background   = '#1b1b1b'
box          = '#3c3836'
primary      = '#3c3836'
error        = '#cc241d'
success      = '#98971a'
color1       = '#458588'
color2       = '#689d6a'
color3       = '#d79921'
color4       = '#d65d0e'
color5       = '#b16286'
color6       = '#b16286'
color7       = '#cc241d'

###
# Configures the OS symbols
###
[os.symbols]
Alpaquita        = " "
Alpine           = " "
AlmaLinux        = " "
Amazon           = " "
Android          = " "
Arch             = " "
Artix            = " "
CachyOS          = " "
CentOS           = " "
Debian           = " "
DragonFly        = " "
Emscripten       = " "
EndeavourOS      = " "
Fedora           = " "
FreeBSD          = " "
Garuda           = "󰛓 "
Gentoo           = " "
HardenedBSD      = "󰞌 "
Illumos          = "󰈸 "
Kali             = " "
Linux            = " "
Mabox            = " "
Macos            = " "
Manjaro          = " "
Mariner          = " "
MidnightBSD      = " "
Mint             = " "
NetBSD           = " "
NixOS            = " "
Nobara           = " "
OpenBSD          = "󰈺 "
openSUSE         = " "
OracleLinux      = "󰌷 "
Pop              = " "
Raspbian         = " "
Redhat           = " "
RedHatEnterprise = " "
RockyLinux       = " "
Redox            = "󰀘 "
Solus            = "󰠳 "
SUSE             = " "
Ubuntu           = " "
Unknown          = " "
Void             = " "
Windows          = "󰍲 "

###
# Configures the OS
###
[os]
format = '[ $symbol](fg:primary bg:color3)'
disabled = false

###
# Configures the directory module
###
[directory]
format = '[$read_only$truncation_symbol](fg:foreground bg:color4)[ $path ](fg:foreground bg:box)'
home_symbol = "󱂵 ~"
read_only = '󰌾 '
read_only_style = ''
truncation_length = 2
truncation_symbol = '󰝰 '

[directory.substitutions]
'/opt/code' = ' code'

###
# Configures the character module
###
[character]
error_symbol = '[χ](bold fg:error)'
format = '$symbol '
success_symbol = '[λ](bold fg:success)'

###
# Configures the fill module
###
[fill]
style  = 'bg:background'
symbol = ' '

###
# Configures the git branch module
###
[git_branch]
format = '[ ](bg:color4)[ $symbol ](fg:color4 bg:background)[$branch ](fg:foreground bg:background)'
symbol = '󰘬'

###
# Configures the git commit module
###
[git_commit]
commit_hash_length = 4
format = "([ 󰓹 ](fg:primary bg:color3)[ $tag ](fg:foreground bg:background))([ 󰜘 ](fg:primary bg:color3)[ $hash ](fg:foreground bg:background))"
only_detached  = false
tag_disabled = false
tag_symbol = ''

###
# Configures the git status module
###
[git_status]
format = '[ ](fg:color3 bg:background)$stashed$staged$deleted$renamed$modified$untracked$ahead_behind$conflicted'
stashed = '[󰏫](fg:color3 bg:background)[ $count ](fg:foreground bg:background)'
ahead = '[󰁝](fg:color2 bg:background)[ $count ](fg:foreground bg:background)'
behind = '[󰁅](fg:color4 bg:background)[ $count ](fg:foreground bg:background)'
diverged = '[󰃻](fg:color7 bg:background)[ $ahead_count $behind_count ](fg:foreground bg:background)'
conflicted = '[󰅙](fg:color7 bg:background)[ $count ](fg:foreground bg:background)'
deleted = '[󰍴](fg:color3 bg:background)[ $count ](fg:foreground bg:background)'
renamed = '[󰑕](fg:color3 bg:background)[ $count ](fg:foreground bg:background)'
modified = '[󰏫](fg:color3 bg:background)[ $count ](fg:foreground bg:background)'
staged = '[󰐕](fg:color2 bg:background)[ $count ](fg:foreground bg:background)'
untracked = '[󰐕](fg:color2 bg:background)[ $count ](fg:foreground bg:background)'

###
# Configures the bun module
###
[bun]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the dart module
###
[dart]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the deno module
###
[deno]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''


###
# Configures the dotnet module
###
[dotnet]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the elixir module
###
[elixir]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the golang module
###
[golang]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the helm module
###
[helm]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the julia module
###
[julia]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the kotlin module
###
[kotlin]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the lua module
###
[lua]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the nodejs module
###
[nodejs]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the php module
###
[php]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the python module
###
[python]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the ruby module
###
[ruby]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the rust module
###
[rust]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the scala module
###
[scala]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the swift module
###
[swift]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = ''

###
# Configures the package module
###
[package]
format = '[ 󰏖 ](fg:primary bg:color4)[ $version ](fg:foreground bg:background)'

###
# Configures the shell module
###
[shell]
disabled = true
format = '[ 󰆍 ](fg:primary bg:color5)[ $indicator ](fg:foreground bg:background)'
unknown_indicator = 'shell'

###
# Configures the time module
###
[time]
disabled    = false
format      = '[ ](bg:color5)[ 󰥔 $time ](fg:color6 bg:background)'
time_format = '%H:%M'

###
# Configures the aws module
###
[aws]
disabled = true
format = '[ ☁︎ ](fg:primary bg:color7)([ $region ](fg:foreground bg:background))'

###
# Configures the docker context module
###
[docker_context]
disabled = false
format = '[ 󰡣 ](fg:primary bg:color1)([ $context ](fg:foreground bg:background))'

###
# Configures the zig module
###
[zig]
format = '[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:background))'
symbol = 'ZIG'
