###
# Starship configuration
###

###
# Configures the starship schema
###
"$schema" = 'https://starship.rs/config-schema.json'

###
# Configures the add newline
###
add_newline = true

###
# Configures the format
###
format = """
[╭](fg:current_line)\
$os\
$directory\
$git_branch$git_status\
$docker_context\
$aws\
$fill\
$php\
$python\
$golang\
$bun\
$dart\
$rust\
$deno\
$julia\
$lua\
$nodejs\
$ruby\
$swift\
$typst\
$time\
$line_break\
[╰─](fg:current_line)\
$character
"""

###
# Configures the palette
###
palette = 'gruvbox'

###
# Configures the rainbow palette
###
[palettes.rainbow]
background   = '#282A36'
box          = '#44475A'
color1       = '#008080'
color2       = '#3CB44B'
color3       = '#FFE119'
color4       = '#0082C8'
color5       = '#F58231'
color6       = '#911EB4'
color7       = '#F032E6'
current_line = '#44475A'
error        = '#E6194B'
foreground   = '#F8F8F2'
primary      = '#1E1F29'
success      = '#3CB44B'

[palettes.gruvbox]
foreground   = '#fbf1c7'
background   = '#3c3836'
box          = '#3c3836'
primary      = '#3c3836'
current_line = '#665c54'
error        = '#cc241d'
success      = '#98971a'
color1       = '#458588' # OS
color2       = '#689d6a' # Directory
color3       = '#d79921' # Git
color4       = '#d65d0e' # Languages
color5       = '#b16286' # Shell
color6       = '#b16286' # Time
color7       = '#cc241d' # Username

###
# Configures the OS
###
# [os]
# format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color1)[ $name ](fg:foreground bg:box)'
# disabled = false

[os.symbols]
Alpaquita        = " "
Alpine           = " "
AlmaLinux        = " "
Amazon           = " "
Android          = " "
Arch             = " "
Artix            = " "
CachyOS          = " "
CentOS           = " "
Debian           = " "
DragonFly        = " "
Emscripten       = " "
EndeavourOS      = " "
Fedora           = " "
FreeBSD          = " "
Garuda           = "󰛓 "
Gentoo           = " "
HardenedBSD      = "󰞌 "
Illumos          = "󰈸 "
Kali             = " "
Linux            = " "
Mabox            = " "
Macos            = " "
Manjaro          = " "
Mariner          = " "
MidnightBSD      = " "
Mint             = " "
NetBSD           = " "
NixOS            = " "
Nobara           = " "
OpenBSD          = "󰈺 "
openSUSE         = " "
OracleLinux      = "󰌷 "
Pop              = " "
Raspbian         = " "
Redhat           = " "
RedHatEnterprise = " "
RockyLinux       = " "
Redox            = "󰀘 "
Solus            = "󰠳 "
SUSE             = " "
Ubuntu           = " "
Unknown          = " "
Void             = " "
Windows          = "󰍲 "


###
# Configures the bun module
###
[bun]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the character module
###
[character]
error_symbol   = '[χ](bold fg:error)'
format         = '$symbol '
success_symbol = '[λ](bold fg:success)'

###
# Configures the dart module
###
[dart]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the deno module
###
[deno]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the directory module
###
[directory]
format            = '[─](fg:current_line)[  ](fg:primary bg:color2)[ $read_only$truncation_symbol$path ](fg:foreground bg:box)'
home_symbol       = "󱂵 ~/"
read_only         = '󰌾 '
read_only_style   = ''
truncation_length = 2
truncation_symbol = '󰝰 '

###
# Configures the dotnet module
###
[dotnet]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the elixir module
###
[elixir]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the fill module
###
[fill]
style  = 'fg:current_line'
symbol = '─'

###
# Configures the git branch module
###
[git_branch]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color3)[ $branch ](fg:foreground bg:box)'
symbol = '󰘬'

###
# Configures the git commit module
###
[git_commit]
commit_hash_length = 4
format             = "([─](fg:current_line)[ 󰓹 ](fg:primary bg:color3)[ $tag ](fg:foreground bg:box))([─](fg:current_line)[ 󰜘 ](fg:primary bg:color3)[ $hash ](fg:foreground bg:box))"
only_detached      = false
tag_disabled       = false
tag_symbol         = ''

###
# Configures the git status module
###
[git_status]
format = '((fg:primary bg:color3)[\[$all_status$ahead_behind\]](fg:foreground bg:box))'

###
# Configures the golang module
###
[golang]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the helm module
###
[helm]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the julia module
###
[julia]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the kotlin module
###
[kotlin]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the lua module
###
[lua]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the nodejs module
###
[nodejs]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the php module
###
[php]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the python module
###
[python]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the ruby module
###
[ruby]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the rust module
###
[rust]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the scala module
###
[scala]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the swift module
###
[swift]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = ''

###
# Configures the package module
###
[package]
format = '[─](fg:current_line)[ 󰏖 ](fg:primary bg:color4)[ $version ](fg:foreground bg:box)'

###
# Configures the shell module
###
[shell]
disabled          = true
format            = '[─](fg:current_line)[ 󰆍 ](fg:primary bg:color5)[ $indicator ](fg:foreground bg:box)'
unknown_indicator = 'shell'

###
# Configures the time module
###
[time]
disabled    = false
format      = '[─](fg:current_line)[ 󰥔 ](fg:primary bg:color1)[ $time ](fg:foreground bg:box)'
time_format = '%H:%M'

###
# Configures the aws module
###
[aws]
disabled = true
format   = '[─](fg:current_line)[ ☁︎ ](fg:primary bg:color7)([ $region ](fg:foreground bg:box))'

###
# Configures the docker context module
###
[docker_context]
disabled = false
format   = '[─](fg:current_line)[ 󰡣 ](fg:primary bg:color1)([ $context ](fg:foreground bg:box))'

###
# Configures the typst module
###
[typst]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = 'TYPST'

###
# Configures the username module
###
[username]
format      = '[─](fg:current_line)[ 󰀄 ](fg:primary bg:color7)[ $user ](fg:foreground bg:box) '
show_always = true

###
# Configures the zig module
###
[zig]
format = '[─](fg:current_line)[ $symbol ](fg:primary bg:color4)([ $version ](fg:foreground bg:box))'
symbol = 'ZIG'