# --- Global Settings ---

# Disables the blank line at the start of the prompt
add_newline               = true

# Defines the overall structure of the prompt
format                    = """\
$os\
$directory\
(\
    $git_branch\
    $git_status\
)\
[ ](fg:arrow)\
$fill\
(\
    $docker_context\
    $php\
    $rust\
    $nodejs\
    $python\
)\
$time\
$cmd_duration
$character\
"""

# --- Palette and Colors ---

palette                   = "normal"

[palettes.normal]
arrow                     = "#353535"
os                        = "#3778BF"
os_admin                  = "#6A040F"
directory                 = "#3F37C9"
node                      = "#417F38"
time                      = "#177E89"
git                       = "#B02B10"
git_status                = "#8B1D2C"
python                    = "#3776AB"
php                       = "#4C588E"
java                      = "#861215"
rust                      = "#C33C00"
golang                    = "#00ADD8"
docker_context            = "#9E2CCD"
clang                     = "#00599D"
duration                  = "#3b8b1c"
text_color                = "#EDF2F4"
text_light                = "#EDF2F4"
error                     = '#E6194B'
success                   = '#3CB44B'

# --- Module Definitions ---

[fill]
style                     = 'fg:arrow'
symbol                    = '─'

[character]
success_symbol            = "[❯](green)"
error_symbol              = "[❯](red)"
vimcmd_symbol             = "[❮](green)"

[directory]
format                    = " [](fg:directory)[ $path ]($style)[$read_only]($read_only_style)[](fg:directory)"
truncation_length         = 2
style                     = "fg:text_color bg:directory"
read_only_style           = "fg:text_color bg:directory"
before_repo_root_style    = "fg:text_color bg:directory"
truncation_symbol         = ""
truncate_to_repo          = true
read_only                 ="  "

[directory.substitutions]
'/opt/code' = ' code'

[time]
disabled                  = false
format                    = " [](fg:time)[ $time]($style)[](fg:time)"
time_format               = "%H:%M"
style                     = "fg:text_color bg:time"

[cmd_duration]
format                    = " [](fg:duration)[ $duration]($style)[](fg:duration)"
style                     = "fg:text_light bg:duration"
min_time                  = 500

[git_branch]
format                    = " [](fg:git)[$symbol$branch](fg:text_light bg:git)[](fg:git)"
symbol                    = " "

[git_status]
format                    = '([ ](fg:git_status)[ $all_status$ahead_behind ]($style)[](fg:git_status))'
style                     = "fg:text_light bg:git_status"

[docker_context]
disabled                  = false
symbol                    = " "
format                    = "[ ](fg:docker_context)[$symbol$context](bg:docker_context fg:text_light)[](fg:docker_context)"

[nodejs]
format                    = "[ ](fg:node)[$symbol$version]($style)[](fg:node)"
style                     = "bg:node fg:text_light"
symbol                    = " "
version_format            = "${raw}"
disabled                  = false

[rust]
format                    = "[ ](fg:rust)[$symbol$version](bg:rust fg:text_color)[](fg:rust)"
symbol                    = " "
version_format            = "${raw}"
disabled                  = false

[php]
format                    = "[ ](fg:php)[$symbol$version](bg:php fg:text_color)[](fg:php)"
symbol                    = " "
version_format            = "${raw}"
disabled                  = false

[python]
disabled                  = false
format                    = '[ ](fg:python)[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)[](fg:python)'
symbol                    = " "
version_format            = "${raw}"
style                     = "fg:text_light bg:python"

[golang]
disabled                  = false
format                    = "[ ](fg:golang)[$symbol$version](bg:golang fg:text_light)[](fg:golang)"
symbol                    = " "
version_format            = "${raw}"

[os]
disabled                  = false
format                    = "[](fg:os)[$symbol]($style)[](fg:os)"
style                     = "fg:text_light bg:os"

[os.symbols]
Alpine                    = " "
Amazon                    = " "
Android                   = " "
Arch                      = " "
CentOS                    = " "
Debian                    = " "
DragonFly                 = " "
Emscripten                = " "
EndeavourOS               = " "
Fedora                    = " "
FreeBSD                   = " "
Gentoo                    = " "
Linux                     = " "
Macos                     = " "
Manjaro                   = " "
Mariner                   = " "
MidnightBSD               = " "
Mint                      = " "
NetBSD                    = " "
NixOS                     = " "
openSUSE                  = " "
Pop                       = " "
Raspbian                  = " "
Redhat                    = " "
RedHatEnterprise          = " "
Redox                     = " "
SUSE                      = " "
Ubuntu                    = " "
Unknown                   = " "
Windows                   = " "
