###
# Starship configuration
###

###
# Configures the starship schema
###
"$schema" = 'https://starship.rs/config-schema.json'

###
# Configures the add newline
###
add_newline = false

###
# Configures the format
###
format = """$directory $character
"""

###
# Configures the palette
###
palette = 'gruvbox'


[palettes.gruvbox]
foreground   = '#fbf1c7'
background   = '#3c3836'
box          = '#3c3836'
primary      = '#3c3836'
line         = '#665c54'
error        = '#cc241d'
success      = '#98971a'
color1       = '#458588'
color2       = '#689d6a'
color3       = '#d79921'
color4       = '#d65d0e'
color5       = '#b16286'
color6       = '#b16286'
color7       = '#cc241d'

###
# Configures the directory module
###
[directory]
format = '$read_only$truncation_symbol $path'
home_symbol = "󱂵 ~"
read_only = '󰌾 '
read_only_style = ''
truncation_length = 2
truncation_symbol = '󰝰 '

[directory.substitutions]
'/opt/code' = ' code'

###
# Configures the character module
###
[character]
success_symbol = "[❯](success)"
error_symbol = "[❯](error)"
vimcmd_symbol = "[❮](success)"
